In [1]:
import torch

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
my_tensor = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], 
    dtype=torch.float32,
    device=device,
    requires_grad=True
)

In [3]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [4]:
# other common initializations
x = torch.empty(size = (3, 3))  # it won't necessarily have zeros but random uninitialized values
print(x)

tensor([[0.0000e+00, 0.0000e+00, 4.2039e-45],
        [0.0000e+00, 4.2039e-45, 7.0065e-45],
        [3.3631e-44, 0.0000e+00, 1.2966e-38]])


In [5]:
x = torch.zeros((3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.rand((3, 3))
print(x)

tensor([[0.9755, 0.8744, 0.1679],
        [0.5800, 0.1940, 0.2344],
        [0.1335, 0.8628, 0.0250]])


In [7]:
x = torch.ones((3, 3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x = torch.eye(5, 6)  # parameters are number of rows and columns
print(x)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])


In [9]:
x = torch.arange(start=0, end=10, step=2) # similar to python's or numpy's range but returns a tensor
print(x)

tensor([0, 2, 4, 6, 8])


In [10]:
x = torch.linspace(start=0.1, end=1, steps=10) # returns 'steps' number of evenly spaced points between start and end
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [11]:
x = torch.empty(size = (1, 5)).normal_(mean=0, std=1)  # normal distribution
print(x)

tensor([[-1.1228,  0.4431,  0.0533, -0.5988,  0.1730]])


In [12]:
x = torch.empty(size = (1, 6)).uniform_(0, 1)  # uniform distribution with lower and upper bound as parameters
print(x)

tensor([[0.7886, 0.4361, 0.2243, 0.0986, 0.0018, 0.0740]])


In [13]:
x = torch.diag(torch.tensor([1, 2, 3, 4, 5]))  # diagonal matrix with given 1D tensor elements on its diagonal
print(x)

x = torch.diag(torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))  # returns the diagonal elements of a 2D tensor as a 1D tensor
print(x)

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]])
tensor([1, 5, 9])


In [14]:
# initializing and converting other data types to tensors and vice versa

tensor = torch.arange(5)
print(tensor)

print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())


tensor([0, 1, 2, 3, 4])
tensor([False,  True,  True,  True,  True])
tensor([0, 1, 2, 3, 4], dtype=torch.int16)
tensor([0, 1, 2, 3, 4])
tensor([0., 1., 2., 3., 4.], dtype=torch.float16)
tensor([0., 1., 2., 3., 4.])
tensor([0., 1., 2., 3., 4.], dtype=torch.float64)


In [15]:
import numpy as np

np_array = np.random.rand(3, 4)
print(np_array)
tensor = torch.from_numpy(np_array)
print(tensor)

np_array_back = tensor.numpy()
print(np_array_back)

[[0.0061551  0.09627458 0.12783287 0.25769863]
 [0.5662331  0.21008473 0.45532354 0.44347462]
 [0.13054085 0.79867284 0.79093836 0.55870721]]
tensor([[0.0062, 0.0963, 0.1278, 0.2577],
        [0.5662, 0.2101, 0.4553, 0.4435],
        [0.1305, 0.7987, 0.7909, 0.5587]], dtype=torch.float64)
[[0.0061551  0.09627458 0.12783287 0.25769863]
 [0.5662331  0.21008473 0.45532354 0.44347462]
 [0.13054085 0.79867284 0.79093836 0.55870721]]


In [28]:
# Tensor math and comparision operations


x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)

z2 = torch.add(x, y)

z = x + y
print(z)

# subtraction
z = x - y

# division
z = torch.true_divide(y, x)  # y = dividend, x = divisor

# inplace operations
t = torch.zeros(3)
t.add_(x)   # methods with underscore at the end are doing inplace operations.
t += x      # inplace increment operator as we see in C and C++
print(t)

# exponentiation
z = x.pow(2)    # places a power of 2 on every element of x
z = x.pow(y)    # places the corresponding element of y as power on each element of x
print(z)        # shapes of x and y should match or kernel will crash.

z = x**2

# comparision
z = x > 2
print(z) # checks the above condidion on every element of the tensor x

# Matmul
x1 = torch.rand(2, 5)
x2 = torch.rand(5, 3)

x3 = torch.mm(x1, x2) # 2x3
x3 = x1.mm(x2)

# matrix exponentiation
matrix_exp = torch.tensor([[1, 3, 4, 6], [4, 5, 2, 6], [3, 5, 1, 6], [6, 1, 9, 3]])
print(matrix_exp. matrix_power(3)) # the matrix_exp must be a square matrix

# elementwise multiplication
z = x * y
print(z)

# dot product
z = torch.dot(x, y)
print(z)

# cross product
z = torch.linalg.cross(x, y)
print(z)

# batch matmul
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)

# Broadcasting
x1 = torch.tensor([[x for x in range(y, y+5)] for y in range(1, 6)])
x2 = torch.arange(start=1, end=6, step=1)

print('x1 :\n', x1)
print('x2 :\n', x2)

z = x1 - x2
z = x1 ** x2

# Other useful tensor operations
sum_x = torch.sum(x1, dim=1)  # sum of all elements along dimension 1 (columns)
values, indices = torch.max(x1, dim=0)  # max value along dimension 0 (rows) and their indices
values, indices = torch.min(x1, dim=1)  # min value along dimension 1 (columns) and their indices   
abs_x = torch.abs(x1)  # absolute value of each element
z = torch.argmax(x1, dim=0)  # indices of max values along dimension 0 (rows)
mean_x = torch.mean(x1.float(), dim=1)  # mean of all elements along dimension 1 (columns)
# torch.mean is only for float tensors, so we convert to float if needed
print(mean_x)




tensor([10, 10, 10])
tensor([2., 4., 6.])
tensor([   1,  256, 2187])
tensor([False, False,  True])
tensor([[ 837,  809,  994, 1236],
        [1028,  957, 1208, 1458],
        [ 905,  868, 1063, 1320],
        [1155,  935, 1369, 1443]])
tensor([ 9, 16, 21])
tensor(46)
tensor([-10,  20, -10])
x1 :
 tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8],
        [5, 6, 7, 8, 9]])
x2 :
 tensor([1, 2, 3, 4, 5])
tensor([3., 4., 5., 6., 7.])
